import Foundation

let appIdentifier = "local.xiaoyu-mac-helper"
let loginItemArgument = "--login-item"
let showControlWindowNotification = Notification.Name("\(appIdentifier).show-control-window")
let capsLockIndicatorEnabledKey = "CapsLockIndicatorEnabled"
let capsLockIndicatorClickToDisableEnabledKey = "CapsLockIndicatorClickToDisableEnabled"
let selectionToolbarEnabledKey = "SelectionToolbarEnabled"
let selectionToolbarSelectAllEnabledKey = "SelectionToolbarSelectAllEnabled"
let selectionToolbarCopyEnabledKey = "SelectionToolbarCopyEnabled"
let selectionToolbarPasteEnabledKey = "SelectionToolbarPasteEnabled"
let selectionToolbarSearchEnabledKey = "SelectionToolbarSearchEnabled"
let selectionToolbarScreenshotEnabledKey = "SelectionToolbarScreenshotEnabled"
let selectionToolbarOrderKey = "SelectionToolbarOrder"
let selectionToolbarHideInFullscreenKey = "SelectionToolbarHideInFullscreen"
let searchURLTemplateKey = "SearchURLTemplate"
let screenshotSaveDirectoryKey = "ScreenshotSaveDirectory"
let screenshotCopiesToClipboardKey = "ScreenshotCopiesToClipboard"
let screenshotSelectsRegionKey = "ScreenshotSelectsRegion"
let activeVisionEnabledKey = "ActiveVisionEnabled"
let desktopLyricsEnabledKey = "DesktopLyricsEnabled"
let desktopLyricsSurfaceEnabledKey = "DesktopLyricsSurfaceEnabled"
let dynamicIslandLyricsEnabledKey = "DynamicIslandLyricsEnabled"
let desktopLyricsWidthKey = "DesktopLyricsWidth"
let desktopLyricsAlignmentKey = "DesktopLyricsAlignment"
let dynamicIslandLyricsWidthKey = "DynamicIslandLyricsWidth"
let dynamicIslandLyricsBlankWidthKey = "DynamicIslandLyricsBlankWidth"
let dynamicIslandLyricsHeightKey = "DynamicIslandLyricsHeight"
let dynamicIslandLyricsBottomRatioKey = "DynamicIslandLyricsBottomRatio"
let dynamicIslandLyricsSlantRatioKey = "DynamicIslandLyricsSlantRatio"
let dynamicIslandLyricsCornerRatioKey = "DynamicIslandLyricsCornerRatio"
let dynamicIslandLyricsFontSizeKey = "DynamicIslandLyricsFontSize"
let dynamicIslandLyricsFontNameKey = "DynamicIslandLyricsFontName"
let dynamicIslandLyricsAlignmentKey = "DynamicIslandLyricsAlignment"
let dynamicIslandLyricsSpectrumEnabledKey = "DynamicIslandLyricsSpectrumEnabled"
let dynamicIslandLyricsHidesOnHoverKey = "DynamicIslandLyricsHidesOnHover"
let menuBarLyricsEnabledKey = "MenuBarLyricsEnabled"
let menuBarLyricsWidthKey = "MenuBarLyricsWidth"
let menuBarLyricsAlignmentKey = "MenuBarLyricsAlignment"
let desktopLyricsSourceOrderKey = "DesktopLyricsSourceOrder"
let desktopLyricsPreferredLanguageKey = "DesktopLyricsPreferredLanguage"
let desktopLyricsShowsTranslationKey = "DesktopLyricsShowsTranslation"
let desktopLyricsFontSizeKey = "DesktopLyricsFontSize"
let desktopLyricsFontNameKey = "DesktopLyricsFontName"
let desktopLyricsTextColorKey = "DesktopLyricsTextColor"
let desktopLyricsStrokeColorKey = "DesktopLyricsStrokeColor"
let desktopLyricsStrokeWidthKey = "DesktopLyricsStrokeWidth"
let desktopLyricsPositionXKey = "DesktopLyricsPositionX"
let desktopLyricsPositionYKey = "DesktopLyricsPositionY"
let desktopLyricsLockedKey = "DesktopLyricsLocked"
let desktopLyricsStylePresetKey = "DesktopLyricsStylePreset"
let musicLyricsAppWhitelistKey = "MusicLyricsAppWhitelist"
let appleMusicMediaUserTokenKey = "AppleMusicMediaUserToken"
let activeVisionPreventDisplaySleepOnGazeKey = "ActiveVisionPreventDisplaySleepOnGaze"
let activeVisionPreventDisplaySleepOnFacingKey = "ActiveVisionPreventDisplaySleepOnFacing"
let activeVisionNotifyWhenExtendingDisplaySleepKey = "ActiveVisionNotifyWhenExtendingDisplaySleep"
let activeVisionLeadTimeBeforeDisplaySleep: TimeInterval = 30
let selectionToolbarDefaultOffMigrationKey = "SelectionToolbarDefaultOffMigrationDone"

// 自更新
let updatePerformFlag = "--perform-update"
let updateQueryURLString = "https://api.pylin.cn/release"
let updateRepo = "PYLinTech/XiaoyuMacHelper"
let updateRootDirectoryName = "XiaoyuMacHelper"
let updatesDirectoryName = "Updates"

func defaultScreenshotDirectoryURL() -> URL {
    FileManager.default.urls(for: .desktopDirectory, in: .userDomainMask).first
        ?? URL(fileURLWithPath: NSHomeDirectory()).appendingPathComponent("Desktop")
}
